Introduce CustomPPOV2 and improve hardware runtime calculation
arthurostrauss/Quantum_Optimal_Control pull request #12
Opened 2024-06-05 09:30 UTC by lukasvoss

This Pull Request introduces new components, such as

**CustomPPOV2 class**
- A unified class that allows for 2 types of training. The usual calibration workflow and the resource-constraint one. The user passes a configuration dictionary that provides the details of how the training shall be performed. Here an example:

```
training_config = {
    'training_mode': 'Normal', # 'hardware_constraint_use_case'
    'training_details': {
        'total_updates': 2_500,
        "target_fidelities": [0.99, 0.999, 0.9999],
        "lookback_window": 10,
        "anneal_learning_rate": True, # TODO: Anneal it down to predefined lowest value, i.e., 5e-5
        "std_actions_eps": 1e-2,
    },   
}
```
The notebook _spillover_noise_gate_level_learning.ipynb_ is demonstrating learning in _Normal_ mode for the pulse spillover case.

**Tracking of hardware runtime during the RL training**
- The ``BackendConfig`` now has an attribute _instruction_durations_dict_ that stores native Instruction Durations of the backend chosen or if these were None, a custom rebuild (same data structure) as generated by a user input providing his gate times assuming all-to-all qubit connectivity.

**Pulse Spillover Noise on the Gate Level**
- We introduce this noise model to mimic the noise that arises in a QPU if a gate operation is being performed on a given qubits, due to the control lines through which the EM pulses are being sent through, neighbouring qubit(s) can also be affected leading to a slight noisy contribution on them as well. We model this strength by the parameter $\gamma$. See the _spillover_noise_q_env_config.py_ script for more detail. We create a custom $RX(\pi/4)$ gate and bind this type of noise to using the AerSimulator as the backend of our choice.
- The script _get_nm_cmaes_ideal_actions_noisy_circ.py_ uses Nelder-Mead (NM) and Covariance Matrix Adaptation Evolution Strategy (CMA-ES) as optimization techniques to find the optimal actions needed to correct the noise effect resulting from a given $(\phi, \gamma)$ which $\phi$ being the angle of the intended rotational gate on the qubit that triggers the noise on its neighbour. The script optimises over the gate fidelity over all 16 input states and saves its result to a pickle file.

**HPO Visualisation**
- Subject of this PR but will become more relevant in the future one(s)
- An analysis script that a user can pass pickle files / directories which these and will visualize the results of a HPO performed on the spillover noise use case as described in the previous bullet point. In particular, the tradeoff between batchsize and number of shots per observable (n_shots) and samplePaulis will be highlighted. Also, the associated resources used to obtain a given level of fidelity, i.e., 0.999 is being shown with the size of the scatter plots. The color of these indicates the noise strength $\gamma$.

2024-06-06 09:08 UTC, arthurostrauss requested changes
Very good job!
Small minor modifications I leave to you before merging. Make sure to pull the latest changes I made on your branch first.

2024-06-06 09:08 UTC, arthurostrauss commented on helper_functions.py
> +def get_baseline_fid_from_phi_gamma(param_tuple):
This function should be in the spillover folder, you can put it into a utils.py

2024-06-06 09:08 UTC, arthurostrauss commented on helper_functions.py
> +    default_instruction_durations_dict = {}
Adding a docstring and a motivation in it would be nice

2024-06-06 09:08 UTC, arthurostrauss commented on ppoV2.py
> +QUANTUM_ENVIRONMENT = Union[
My advice is that now that we finally got the BaseQuantumEnvironment, you can use it in the Union instead (so Union[QuantumEnvironment, ContextAwareQuantumEnvironment, BaseQuantumEnvironment]). In the very near future we'll only care about the V2 versions anyway.

2024-06-08 03:27 UTC, lukasvoss commented
I implemented your suggestions. Please let me know in case of further work needed.
Please do not delete this branch after a merge, as I would like to continue working on it for the hpo etc.

2024-06-08 03:28 UTC, lukasvoss commented on ppoV2.py
> +QUANTUM_ENVIRONMENT = Union[
I removed the V2 versions from the constant.

2024-06-08 03:30 UTC, lukasvoss commented on helper_functions.py
> +    default_instruction_durations_dict = {}
Added documentation and slightly changed the function signature. ``gates_done_by_software `` is now optional and with default value None, that's why it's now at the end since it has a default argument. I adjusted the relevant parts where this function is called.

2024-06-08 03:31 UTC, lukasvoss commented on helper_functions.py
> +def get_baseline_fid_from_phi_gamma(param_tuple):
Moved it to a noise utils file I had that was not part of the PR. The other functions in there are not used in any other scripts. These are e.g., implementations of the random kraus channel noise that we discussed with Hui Khoon earlier this year.

2024-06-10 01:46 UTC, arthurostrauss requested changes
We're very close. Just a few more minor comments to make it squeaky clean and we should be good to merge.

2024-06-10 01:46 UTC, arthurostrauss commented on gate_level_abstraction/spillover_noise_use_case/noise_utils/utils.py
> +    inst: Instruction, qargs: Qubit, gate_count: Dict, circuit_context: QuantumCircuit
I'm confused about the type hint of qargs here, shouldn't it be a QuantumRegister instead?

2024-06-10 01:46 UTC, arthurostrauss commented on gate_level_abstraction/spillover_noise_use_case/spillover_noise_q_env_config.py
> +    rx_op_2q = Operator(identity_op.tensor(rx_op))
The output of the operation tensor you do is already an Operator, no need to wrap it in another Operator declaration

2024-06-10 01:46 UTC, arthurostrauss commented on helper_functions.py
> +        gates_done_by_software (list): A list of gates that are performed by software and have zero duration.
I would suggest the name `virtual_gates` instead of gates_done_by_software for clarity.

2024-06-10 01:46 UTC, arthurostrauss commented on template_configurations/qiskit/gate_level/q_env_config.py
> +        gates_done_by_software = ["rz", "s", "t"]
Same suggestion of name changing here.

2024-06-11 02:09 UTC, lukasvoss commented on gate_level_abstraction/spillover_noise_use_case/noise_utils/utils.py
> +    inst: Instruction, qargs: Qubit, gate_count: Dict, circuit_context: QuantumCircuit
Here a quick example to why I chose the type hint `Qubit`:

```
from qiskit import QuantumCircuit

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)

for inst, qargs, _  in qc.data:
    print('Instruction:', inst)
    print('Qubits:', qargs)
```

This prints: 

```
Instruction: Instruction(name='h', num_qubits=1, num_clbits=0, params=[])
Qubits: [Qubit(QuantumRegister(2, 'q'), 0)]
Instruction: Instruction(name='cx', num_qubits=2, num_clbits=0, params=[])
Qubits: [Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)]
```

So, qargs is a list of Qubits(QuantumRegister()) for each instruction in a quantum circuit. A single element in this list if of type `qiskit.circuit.quantumregister.Qubit`. The `Qubit` class inherits from the `Bit` class and needs a `QuantumRegister` carrying that bit.

Both type hints should be valid, let me know which one you prefer.

Here the `Qubit` class for reference:

```
class Qubit(Bit):
    """Implement a quantum bit."""

    __slots__ = ()

    def __init__(self, register=None, index=None):
        """Creates a qubit.

        Args:
            register (QuantumRegister): Optional. A quantum register containing the bit.
            index (int): Optional. The index of the bit in its containing register.

        Raises:
            CircuitError: if the provided register is not a valid :class:`QuantumRegister`
        """

        if register is None or isinstance(register, QuantumRegister):
            super().__init__(register, index)
        else:
            raise CircuitError(
                "Qubit needs a QuantumRegister and %s was provided" % type(register).__name__
            )
```

2024-06-11 02:17 UTC, arthurostrauss commented on gate_level_abstraction/spillover_noise_use_case/noise_utils/utils.py
> +    inst: Instruction, qargs: Qubit, gate_count: Dict, circuit_context: QuantumCircuit
Okay I understand better. So qargs type hint should be in general `Sequence[Qubit]`(tuple or list of Qubits)

2024-06-11 02:25 UTC, arthurostrauss approved these changes

2024-06-11 02:25 UTC, merged