Improvement of the HPO wrapper and Handling Training Configuration & Introduction of SpilloverNoiseQuantumEnvironment and
arthurostrauss/Quantum_Optimal_Control pull request #13
Opened 2024-06-15 04:27 UTC by lukasvoss

This PR extends the current capabilities on how to use the hyperparameter optimization (HPO) wrapper, introduces a new approach to how a user sets up his RL training agent and adds a new dedicated class for dealing with the Pulse Spillover Noise use case.

**HPO Wrapper**
- Can be used for all calibration tasks and will handle the individual cases based on the provided input configurations
- Automatically adjusts the number repetitions of the target gate in the spillover noise use case for a given target fidelity and noise profile $(\phi, \gamma)$

**Improved Handling of how to specify the training parameters**
- All RL training-related settings are now to be set in dedicated dataclasses: See the file _hpo_training_config.py_ that both has the associated dataclasses for an hop-case and normal training case
- The user can set 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Between two types of training constraints (total number of updates or a maximum associated hardware runtime) 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - logging behaviour of the agent, learning rate annealing, live plotting, target fidelities, set a threshold that stops the training if the standard deviations of the actions are below it, how large the lookback of the sliding window approach is (that records the surpassing of the provided target fidelities), and beyond

**Dedicated class PulseSpilloverQuantumEnvironment for this use case**
- Inherits from the `ContextAwareQuantumEnvironmentV2` and takes the $(\phi, \gamma)$ tuple as additional argument
- Class has a function that sets the _n_reps_ of the environment to the number needed amplify the noise profile below the lowest target fidelity value provided to the function

- There is a ReadMe file for the Pulse Spillover Noise use case

2024-06-16 09:31 UTC, arthurostrauss requested changes
Excellent job. Just one last thing to address in your HPO, it still carries a property reminiscent of your custom use case.

2024-06-16 09:31 UTC, arthurostrauss commented on context_aware_quantum_environment.py
> +    def update_circuit_fidelity_history(self, output_states, baseline_circ):
I removed this method in the latest file because it was not adding anything useful.

2024-06-16 09:31 UTC, arthurostrauss commented on context_aware_quantum_environment.py
> +class SpilloverNoiseQuantumEnvironment(ContextAwareQuantumEnvironmentV2):
Move your custom class in a separate Python file. This will be in your custom use case folder.

2024-06-16 09:31 UTC, arthurostrauss commented on hyperparameter_optimization.py
> +    def gamma(self):
The HPO should not have such property. Are you still using it in the main code? If yes, then we should find a workaround, if not you can just remove it.

2024-06-16 14:04 UTC, lukasvoss commented on hyperparameter_optimization.py
> +    def gamma(self):
Good catch, you're right. I made phi and gamma a property of the `SpilloverNoiseQuantumEnvironment` that we can access from the HPO in the relevant lines that already check that our env is of this instance.

2024-06-16 14:04 UTC, lukasvoss commented on context_aware_quantum_environment.py
> +    def update_circuit_fidelity_history(self, output_states, baseline_circ):
Removed it. Did I see it right, that this function was a duplicate?

2024-06-16 14:04 UTC, lukasvoss commented on context_aware_quantum_environment.py
> +class SpilloverNoiseQuantumEnvironment(ContextAwareQuantumEnvironmentV2):
Moved it.

2024-06-17 00:34 UTC, arthurostrauss commented on hyperparameter_optimization.py
> +    def gamma(self):
We should therefore discuss where in the HPO do you need this information, as I still believe it should not carry any information about the subclasses you have created for a custom use case. I seem to have located references to phi and gamma only for logging options. What I suggest you therefore do is that you proceed to a similar fashion to what you did with the modify_env_parameters, you create a method in the base class rendering your environment when summoned for printing/logging info, and you override it in your custom environment to log the info about gamma and phi. This way, you avoid yourself the trouble of this if/elif statement for each possible subclass of the QEnv you might do in the future.

2024-06-17 00:39 UTC, arthurostrauss requested changes
Nearly there,  the last comments I have are for really clearing your HPO code to any specific dependency to use cases that could be multiplied in the future.

2024-06-17 00:39 UTC, arthurostrauss commented on hyperparameter_optimization.py
>              param_str = "phi: {}pi; gamma: {}; Baseline Fidelity: {}; ".format(
So this is the line I'm talking about. The idea is good, but the method for rendering this string param should be in the environment. There is already a method call __repr__ which returns a string for printing info about the env. You could choose to override this one if relevant, or just create your custom one that you call here in the base class.

2024-06-17 00:39 UTC, arthurostrauss commented on hyperparameter_optimization.py
> +            start_file_name = f"phi-{self.q_env.unwrapped.phi/np.pi}pi_gamma-{round(self.q_env.unwrapped.gamma, 2)}"
I would definitely add a _label method to the environment that I call here. The label would be this name you want to give or an updated version of this.

2024-06-19 03:01 UTC, arthurostrauss requested changes
There are still a few traces of your custom use case in your HPO. Other small changes requested but the core is there.

2024-06-19 03:01 UTC, arthurostrauss commented on context_aware_quantum_environment.py
> +from abc import abstractmethod
Check that you don't have unused imports here.

2024-06-19 07:45 UTC, arthurostrauss requested changes

2024-06-19 07:45 UTC, arthurostrauss commented on ppoV2.py
> +    next_obs, reward, terminated, truncated, infos = env.unwrapped.step(action.cpu().numpy())
No on the contrary, you want to use the step function of the wrapped environment (to enable the RescaleAction and ClipAction). Overall, remove the unwrapped when the attribute you're looking for is actually belonging to the Wrapper (observation space, action space, step)

2024-06-19 07:45 UTC, arthurostrauss commented on ppoV2.py
> +        self.env.unwrapped.clear_history()
I'm not sure to see why this is necessary here. Perhaps you want to clear the history in the frame of the HPO, but a PPO could act on an environment that already has a history in principle

2024-06-19 07:45 UTC, arthurostrauss commented on ppoV2.py
> +        env.unwrapped.observation_space,
Remove unwrapped.

2024-06-19 07:45 UTC, arthurostrauss commented on ppoV2.py
> +        env.unwrapped.observation_space, hidden_units, activation_functions, chkpt_dir_critic
Remove unwrapped.

2024-06-19 08:22 UTC, arthurostrauss approved these changes

2024-06-19 08:22 UTC, merged