Enable custom noise models on the circuit-level | Circuit decomposition in custom unique unitaries
arthurostrauss/Quantum_Optimal_Control pull request #8
Opened 2024-03-19 08:41 UTC by lukasvoss

This PR introduces 2 features:

1. Custom noise models that can be bound to specific target gates or form a local circuit context (see spillover noise model)
2. A function that rebuilds an arbitrary, non-parametrized circuit with custom, unitary operations making each gate uniquely addressable (e.g., for binding noise)

**Spillover Noise Model**
To model pulse-spillover on a circuit level description of QC, we prepend a RX($\phi$) operation on qubit 0 and a CRX($\gamma \phi)$ gate between qubit 0 and 1 with rotation angle $\phi$ and spillover rate $\gamma$. This will mimic the effect of pulse-spillover which is a type of noise arising in hardware. I can occur due to wires through with signals are sent to address qubits on a chip are very close to each other than neighboring qubits can experience contributions even though they are not the intended recipient of this pulse.

**Custom Noise Models**
1. Over-rotation error for single-qubit rotational gates
2. Random noise for arbitrary system size with Kraus operators

Can be found in _template_configurations/qiskit/gate_level/noise_utils_

**HPO demonstration notebook**
This notebook uses the Spillover Noise Model and applies the HPO wrapper on it trying to minimize the cost function taking into account multiple penalty weights for experimentally-costly operations such as batchsize, n_shots, Paulis_observables etc.

2024-03-19 08:45 UTC, lukasvoss commented
I resolved the merge conflict that was present due to the observation space in the ContextAwareQuantumeEnvironment script. I kept my version that has it as a 2D Box and commented out the higher-dimensional one.

2024-03-19 12:38 UTC, arthurostrauss requested changes
Very good work! Very minor comments to address, but great job in the documentation and the conciseness of the code!

2024-03-19 12:38 UTC, arthurostrauss commented on .gitignore
Try to discard this file in your PR.

2024-03-19 12:38 UTC, arthurostrauss commented on template_configurations/qiskit/gate_level/hpo_results/custom_cost_value_16.505404_timestamp_19-03-2024-16-02-54.pickle
To be set in custom folder.

2024-03-20 01:40 UTC, lukasvoss commented on quantumenvironment.py
> +            full_circ = qc.compose(input_state_circ, inplace=False, front=True)
Find the error message attached as a txt file. It works for other parametrized circuits, I think it's due to the custom unitary gate we define in this case that it fails.
[error_message_passmanager.txt](https://github.com/arthurostrauss/Quantum_Optimal_Control/files/14661218/error_message_passmanager.txt)


**That's the code used**

import numpy as np
from qiskit.circuit.library import RXGate, SXGate, IGate, CRXGate
from qiskit.quantum_info import Operator

from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit.transpiler import Layout, InstructionProperties
from qiskit_ibm_runtime.fake_provider import FakeJakartaV2
from qiskit.circuit import Qubit, QuantumRegister, QuantumCircuit, ParameterVector
from qiskit_experiments.library.tomography.basis import (
    PauliPreparationBasis,
    Pauli6PreparationBasis,
)
from qiskit.providers.fake_provider import GenericBackendV2
from qiskit_aer import AerSimulator
import qiskit_aer.noise as noise


phi = np.pi/4 # rotation angle
gamma = 0.01 # spillover rate for the CRX gate
custom_rx_gate_label = 'custom_kron(rx,ident)_gate'

noise_model = noise.NoiseModel()
coherent_crx_noise = noise.coherent_unitary_error(CRXGate(gamma*phi))
noise_model.add_quantum_error(coherent_crx_noise, [custom_rx_gate_label], [0, 1])
noise_model.add_basis_gates(['unitary'])

generic_backend = GenericBackendV2(num_qubits=2, dtm=2.2222*1e-10, basis_gates=["cx", "id", "rz", "sx", "x", "crx"])
backend = AerSimulator.from_backend(
    generic_backend,
    noise_model=noise_model)

pm = generate_preset_pass_manager(
    optimization_level=1,
    backend=backend, # FakeJakartaV2(),
    initial_layout=Layout({
        0: Qubit(QuantumRegister(2, 'q'), 0),
        1: Qubit(QuantumRegister(2, 'q'), 1)
    }),
)

params = ParameterVector('a', 1)
qc = QuantumCircuit(2)
rx_op = Operator(RXGate(phi))
identity_op = Operator(IGate())
rx_op_2q = Operator(identity_op.tensor(rx_op))
qc.unitary(rx_op_2q, [0, 1], label=custom_rx_gate_label)

input_state_circ = QuantumCircuit(2)
# PauliPrepYp
input_state_circ.h(0)
input_state_circ.s(0)
# PauliPrepXp
input_state_circ.h(1)

print(input_state_circ)


full_circ = pm.run(qc.compose(input_state_circ, inplace=False, front=True))
# full_circ = qc.compose(input_state_circ, inplace=False, front=True)
print(full_circ)

2024-03-20 03:15 UTC, lukasvoss commented on helper_functions.py
> +    return config
Yes, it should serve both cases as the YAML file keys will be read and translated to a Python dictionary that uses the keys as found in the YAML file. 
Therefore, an additional mapping, as e.g., 

```
{
    "CLIP_RATIO": config["CLIP_RATIO"],
}
```

is redundant. Exactly this will heady with YAML safe_load.

In the _helper_files.py_, I now update the hpo_config dictionary with the key-value pairs present in the agent_config dictionary but not present in the hpo_config. So, the hpo-related values are being kept.

2024-03-20 03:15 UTC, lukasvoss commented on hyperparameter_optimization.py
> +        self.agent_config_init = load_from_yaml_file(path_agent_config)
In these notebooks the function body was basically coded once again, I commented out the current version and added getting the agent_config using the function from the helper_functions script.

2024-03-20 03:15 UTC, lukasvoss commented on template_configurations/qiskit/gate_level/q_env_config.py
I created a new file _correlated_noise_q_env_config.py_ in the subdirectory _noisy_circuit_ that is basically the q_env_config.py file but with the custom correlated noise.
In the gate_level directory, the q_env_config file is back your original noise-free version.

2024-03-20 03:16 UTC, lukasvoss commented on template_configurations/qiskit/gate_level/q_env_gate_config.yml
File is called noise_q_env_gate_config.yml and to be found in subdirectory of gate_level called _noisy_circuit_.

2024-03-20 03:16 UTC, lukasvoss commented on template_configurations/qiskit/gate_level/spillover_noise_gatel_level_learning.ipynb
Done.

2024-03-20 03:16 UTC, lukasvoss commented on template_configurations/qiskit/gate_level/hpo_results/custom_cost_value_16.505404_timestamp_19-03-2024-16-02-54.pickle
Done.

2024-03-20 03:19 UTC, lukasvoss commented on template_configurations/qiskit/hpo_config.yaml
File now called _noise_hpo_config.yaml_.

2024-03-20 03:26 UTC, lukasvoss commented on .gitignore
Done.

2024-03-20 04:55 UTC, arthurostrauss approved these changes

2024-03-20 04:55 UTC, merged