[Add Feature] Simulate ZZ-Crosstalk in the custom backend for pulse level simulation
arthurostrauss/Quantum_Optimal_Control pull request #9
Opened 2024-03-22 03:47 UTC by lukasvoss

This PR introduces the option of passing a `Dict[Tuple[int, int], float] ` to the `custom_backend` function that stores noise-couplings strengths between qubits.

If not specified otherwise, the noise profile is considered to be **symmetrical** allowing to only pass one noise-direction $(i, j): \gamma$ without the need to also pass the counter-direction $(j, i): \gamma$.

2024-03-22 08:00 UTC, arthurostrauss commented on template_configurations/qiskit/pulse_level/dynamics_backends/noisy_circuit/noisy_dynamics_config.py
> +    jax_solver = JaxSolver(
Same argument here for what follows, since this is a replication of the previous code, should be embedded into a function to be called again. The goal is to avoid copy past as much as possible.

2024-03-22 10:15 UTC, arthurostrauss requested changes
Thanks for the quick edits. Just have to put all the added functions to another dedicated utils file, and also precise that this is pulse spillover and not static ZZ crosstalk (unless I'm mistaken). 
You can do the same reasoning for the functions that are used for custom Aer backends with gate level custom noise models.

2024-03-22 10:15 UTC, arthurostrauss commented on helper_functions.py
Those added functions are not really necessary for the whole functioning of the workflow. They should therefore be packed in another utils.py present in the dynamics_backend folder in template configurations instead.

2024-03-22 10:15 UTC, arthurostrauss commented on helper_functions.py
> +    Self-loops can optionally be included if they exist and have positive coupling strength.
What would self loop correspond to? Some distortion on the baseline pulse? If yes, this will not be very be useful if it's not stochastic. We could however think about how to implement another noise model which implements the signal with some white noise. Food for thought for later.

2024-03-22 10:15 UTC, arthurostrauss commented on helper_functions.py
> +    between these qubits. Only positive coupling strengths are considered as valid connections.
You should explain how those couplings differ from the original ones present in the baseline function. This is a coupling that exists only when a pulse is played no?

2024-03-22 10:15 UTC, arthurostrauss commented on helper_functions.py
> -    target_gate_instruction = kwargs.get('gate')
The function create_circuit_from_own_unitaries should also be part of another dedicated utils file for the gate level. Not necessary for the functioning of the workflow.

2024-03-22 10:15 UTC, arthurostrauss commented on helper_functions.py
> +def process_gate(
Same comment for going into another utils file for this method

2024-03-22 10:15 UTC, arthurostrauss commented on template_configurations/qiskit/pulse_level/dynamics_backends/dynamics_config.py
> +from helper_functions import (
Okay but should be imported from dedicated utils.

2024-03-22 10:15 UTC, arthurostrauss commented on template_configurations/qiskit/pulse_level/dynamics_backends/noisy_circuit/noisy_dynamics_config.py
> +from helper_functions import (
Same comment as before (import from utils)

2024-03-22 10:15 UTC, arthurostrauss commented on template_configurations/qiskit/pulse_level/dynamics_backends/noisy_circuit/noisy_dynamics_config.py
> +    This noise occurs when pulses are applied to one qubit and affect the neighbouring qubits as well due to wires being close to each other.
I'm confused. This noise is the pulse spillover right? The ZZ crosstalk interaction is part of the static hamiltonian, and not part of the driving operators.

2024-03-23 01:35 UTC, lukasvoss commented on helper_functions.py
> +    Self-loops can optionally be included if they exist and have positive coupling strength.
Agreed, I removed this. Let's dedicate another model to imperfect pulses at some point in the future.

2024-03-23 01:36 UTC, lukasvoss commented on helper_functions.py
> +    between these qubits. Only positive coupling strengths are considered as valid connections.
Added some clarifying documentation.

2024-03-23 01:37 UTC, lukasvoss commented on template_configurations/qiskit/pulse_level/dynamics_backends/noisy_circuit/noisy_dynamics_config.py
> +    This noise occurs when pulses are applied to one qubit and affect the neighbouring qubits as well due to wires being close to each other.
Yes, it wrote the wrong noise type here, it should say pulse-spillover. Updated the docstring.

2024-03-23 01:41 UTC, lukasvoss commented
First things first: The features introduced are for modeling pulse-spillover noise arising from control lines in real hardware being very close to each other that neighbouring qubits can be effected when playing a pulse on a certain qubit.
Passing the dictionary of couplings, we can specify between which qubit pairs this noise arises and by what spillover rate $\gamma$ the qubit is affected.

I moved the responsible functions into a utils file and updated documentation.

2024-03-25 03:15 UTC, arthurostrauss requested changes
Just an adjustment in the docstrings and we should be good to go.

Good work!

2024-03-25 03:15 UTC, arthurostrauss commented on template_configurations/qiskit/gate_level/noisy_circuit/utils.py
> +            isinstance(target_gate_instruction, Instruction)
Could the elements inside the circuit.data be something else than Instruction ? Can't think of an example now but I'd be happy to hear about it.

2024-03-25 03:15 UTC, arthurostrauss commented on template_configurations/qiskit/pulse_level/dynamics_backends/utils.py
> +    This is a common noise source in superconducting qubits.
Given the poor literature I could find on this noise source I would not say it is considered common. The question of it being neglected now because it is solved or because it is just not well studied is not answered yet?

2024-03-25 04:28 UTC, arthurostrauss approved these changes

2024-03-25 04:30 UTC, merged